// src/App.svelte
<script>
    import Game from "./lib/Game.svelte";
    import Peer from "peerjs";
    import { onDestroy } from "svelte";

    const peer = new Peer();

    let peerId;
    let connections = {};

    peer.on("open", (id) => {
        console.log("My peer ID is: " + id);
        peerId = id;
    });
    peer.on("connection", (conn) => {
        setupConnectionHandlers(conn);
    });
    peer.on("error", (err) => {
        console.error(err);
    });

    // ACTION EVENTS
    const actionListeners = [];
    function registerActionListener(callback) {
        actionListeners.push(callback);
    }
    function unregisterInputListener(callback) {
        const index = actionListeners.indexOf(callback);
        if (index !== -1) {
            actionListeners.splice(index, 1);
        }
    }
    function dispatchAction(event) {
        actionListeners.forEach((callback) => {
            callback(event);
        });
    }
    function handleInput(e) {
        let action;
        switch (e.key) {
            case "ArrowLeft":
                action = "LEFT";
                break;
            case "ArrowRight":
                action = "RIGHT";
                break;
            case "ArrowUp":
                action = "ROTATE";
                break;
            case "ArrowDown":
                action = "DOWN";
                break;
            case " ":
                action = "DROP";
                break;
        }
        if (action) {
            const event = {
                action: action,
                peerId: peerId,
            };
            dispatchAction(event);
            // Send action to all connected peers
            for (const conn of Object.values(connections)) {
                conn.send(event);
            }
        }
    }
    window.addEventListener("keydown", handleInput);

    // PEER CONNECTION
    function handleClickConnect() {
        let code = window.prompt("Enter peer ID");
        if (code) {
            const conn = peer.connect(code);
            setupConnectionHandlers(conn);
        }
    }
    function handleClickDisconnect() {
        for (const conn of Object.values(connections)) {
            conn.close();
        }
        connections = {};
    }

    function setupConnectionHandlers(conn) {
        conn.on("open", () => {
            console.log("Connected to peer ", conn.peer);
            connections[conn.peer] = conn;
            connections = { ...connections};
        });
        conn.on("data", (data) => {
            console.log("Received", data);
            dispatchAction(data);
        });
        conn.on("close", () => {
            console.log("Connection closed");
            delete connections[conn.peer];
            connections = { ...connections};
        });
    }
    // HELPER FUNCTIONS
	$: isConnected = () => Object.keys(connections).length > 0;

    // CLEANUP
    onDestroy(() => {
        window.removeEventListener("keydown", handleInput);
        for (const conn of Object.values(connections)) {
            conn.close();
        }
        peer.destroy();
    });
</script>

<main>
    <div class="mb-29">
        <h1 class="mb-2 font-bold tracking-tight sm:text-4xl">
            Tetrominos Battle Royale
        </h1>

        {#key connections}
            {#if peerId}
                <p>
                    Your ID is:
                    <br />
                    <strong>{peerId}</strong>
                </p>
                <button
                    class="mt-2 rounded-md bg-white px-3.5 py-2.5 text-sm font-semibold text-gray-900 shadow-sm hover:bg-gray-100 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white"
                    on:click={() => handleClickConnect()}
                >
                    Connect
                </button>
            {:else if Object.keys(connections).length === 0}
                <p>Connecting...</p>
            {:else}
                <button
                    class="mt-2 rounded-md bg-white px-3.5 py-2.5 text-sm font-semibold text-gray-900 shadow-sm hover:bg-gray-100 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white"
                    on:click={() => handleClickDisconnect()}
                >
                    Disconnect
                </button>
            {/if}
        {/key}
    </div>
    <div class="mt-4 flex flex-row gap-4 items-center justify-center">
        <Game {peerId} seed={43} {registerActionListener} />
        {#each Object.keys(connections) as connId}
            <Game peerId={connId} seed={43} {registerActionListener} />
        {/each}
    </div>
</main>

<style global lang="postcss">
    @tailwind utilities;
    @tailwind components;
    @tailwind base;
</style>

// src/App.jsx
import React, { useEffect, useRef, useState } from "react";
import { createCustomEvent } from "./utils/customEvents";
import { useEvent } from "./context/EventContext";
import "./App.css";
import Peer from "peerjs";
import Game from "./Game";

const peer = new Peer();

function App() {
    const { dispatchEvent } = useEvent();
    const [peerId, setPeerId] = useState("");
    const [connections, setConnections] = useState([]);

    // Handle input from the user
    function handleInput(e) {
        let action;
        switch (e.key) {
            case "ArrowLeft":
                action = "LEFT";
                break;
            case "ArrowRight":
                action = "RIGHT";
                break;
            case "ArrowUp":
                action = "ROTATE";
                break;
            case "ArrowDown":
                action = "DOWN";
                break;
            case " ":
                action = "DROP";
                break;
        }
        if (action) {
            console.log("Peer ID: " + peerId + " Action: " + action);
            const event = createCustomEvent("input", {
                action: action,
                peerId: peerId,
            });
            dispatchEvent(event);
            sendInput(event);
            console.log("Sent input ", event.detail);
        }
    }
    // Send input to all connected peers
    function sendInput(event) {
        connections.forEach((conn) => {
            if (conn.open) {
                conn.send(event);
            }
        });
    }
    function handlePeerInput(event) {
        // Propagate the event to the game
        // TODO: Validation
        dispatchEvent(event);
    }

    function setupConnectionHandlers(conn) {
        conn.on("data", (event) => {
            handlePeerInput(event);
        });

        conn.on("close", () => {
            setConnections(connections.filter((c) => c !== conn));
        });
    }

    function handleClickConnect() {
        let code = window.prompt("Enter peer ID");
        if (code) {
            console.log("Connecting to peer ", code);
            const conn = peer.connect(code);
            if (!conn) {
                console.error("Failed to connect to peer ", code);
                return;
            }
            setupConnectionHandlers(conn);
            setConnections((prevConnections) => [...prevConnections, conn]);
        }
    }
    function handleClickDisconnect() {
        for (let conn of connections) {
            conn.close();
        }
        setConnections([]);
    }
    useEffect(() => {
        peer.on("open", (id) => {
            setPeerId(id);
            console.log("My peer ID is: " + id);
        });
        peer.on ("error", (error) => {
            console.error("Peer error ", error);
        });
        peer.on("connection", (conn) => {
            if (connections.some((c) => c.peer === conn.peer)) {
                console.warn("Already connected to peer ", conn.peer);
                return;
            }
            console.log("Peer connected ", conn.peer);
            setConnections((prevConnections) => [...prevConnections, conn]);
            setupConnectionHandlers(conn);
        });
        document.addEventListener("keydown", handleInput);
        return () => {
            document.removeEventListener("keydown", handleInput);
            peer.disconnect();
        };
    }, []);

    return (
        <>
            <div className="mb-29">
                <h1 className="mb-2 font-bold tracking-tight sm:text-4xl">
                    Tetrominos Battle Royale
                </h1>
                <p>
                    Your ID is:
                    <br />
                    <strong>{peerId}</strong>
                </p>
            </div>
            <div className="flex-col flex gap-2 justify-center items-center">
                {peerId && connections.length > 0 && (
                    <div className="flex flex-row justify-center m-3">
                        <Game peerId={peerId} seed={43} />
                        {connections.map((conn) => (
                            <div key={conn.peer}>
                                <Game peerId={conn.peer} seed={43} />
                            </div>
                        ))}
                    </div>
                )}
                {!peerId && <p>Waiting for peer connection...</p>}
                {peerId && connections.length === 0 && (
                    <>
                    <button
                        className="rounded-md bg-white px-3.5 py-2.5 text-sm font-semibold text-gray-900 shadow-sm hover:bg-gray-100 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white"
                        onClick={() => handleClickConnect()}
                    >
                        Connect to peer
                    </button>
                    <Game peerId={peerId} seed={43} />
                    </>
                )}
                {connections.length > 0 && <button className="rounded-md bg-white px-3.5 py-2.5 text-sm font-semibold text-gray-900 shadow-sm hover:bg-gray-100 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white" onClick={() => handleClickDisconnect()}>
                    Disconnect
                </button>}
                <div className=" text-left mx-auto w-auto inline-block">
                    ↑ &emsp;&emsp;&ensp; Rotate
                    <br />
                    ← &emsp;&emsp;&ensp;Move left
                    <br />
                    → &emsp;&emsp;&ensp;Move right
                    <br />
                    ↓ &emsp;&emsp;&ensp; Move down
                    <br />
                    SPACE &nbsp; Drop
                </div>
            </div>
        </>
    );
}

export default App;
